export type Work = {
  slug: string;
  number: string;
  title: string;
  englishTitle: string;
  chapter: 'gaze' | 'borrowed' | 'cycle' | 'prologue';
  width: number;
  height: number;
  alt: string;
  short: string;
  note: string;
  context?: string;
  accent: 'blue' | 'red' | 'green' | 'ink';
  image: {
    large: string;
    thumb: string;
  };
};

const image = (slug: string) => ({
  large: `/images/${slug}-large.webp`,
  thumb: `/images/${slug}-thumb.webp`,
});

export const works: Work[] = [
  {
    slug: '01-panel-city',
    number: '01',
    title: '分镜里的城市',
    englishTitle: 'A City in Panels',
    chapter: 'borrowed',
    width: 4096,
    height: 2828,
    alt: '黑白手绘漫画分镜中出现多个人物与表情，中央是醒目的游戏式标题。',
    short: '分镜把人物、表情与城市噪声压缩在同一张纸上。',
    note: '一格接一格，熟悉的视觉符号被重新排列。画面像一块喧闹的记忆墙，也像进入另一座城市前的地图。',
    context: '含流行文化与游戏视觉元素，作为个人手绘练习呈现。',
    accent: 'ink',
    image: image('01-panel-city'),
  },
  {
    slug: '02-fractured-rose',
    number: '02',
    title: '裂缝中的玫瑰',
    englishTitle: 'Rose Among Fragments',
    chapter: 'cycle',
    width: 3992,
    height: 4096,
    alt: '一枝深色玫瑰竖立在由不规则浅色几何碎片构成的背景上。',
    short: '一枝玫瑰从彼此错开的平面中生长出来。',
    note: '背景被切成许多不稳定的片段，花茎却保持笔直。柔软与锋利、脆弱与坚持在同一画面里相遇。',
    accent: 'red',
    image: image('02-fractured-rose'),
  },
  {
    slug: '03-blue-eyes',
    number: '03',
    title: '目光',
    englishTitle: 'The Gaze',
    chapter: 'gaze',
    width: 2792,
    height: 2659,
    alt: '一双钴蓝色眼睛透过遮住面部的手指向外凝视。',
    short: '唯一的蓝色停在眼睛里，穿过指间看向画外。',
    note: '手遮住了面孔，却让目光变得更加直接。画面中的人看向观众，观看由此不再是单向的。',
    accent: 'blue',
    image: image('03-blue-eyes'),
  },
  {
    slug: '04-bridge-storm',
    number: '04',
    title: '桥与风暴',
    englishTitle: 'Bridge Before the Storm',
    chapter: 'cycle',
    width: 3548,
    height: 2566,
    alt: '密集黑色线条画出乌云、山谷与一座桥，远处有红色几何结构。',
    short: '桥伸向山谷，红色结构在风暴下若隐若现。',
    note: '重复线条构成云层与草木的压力，桥成为画面唯一清晰的通路。它通向哪里，仍留在风暴之后。',
    accent: 'red',
    image: image('04-bridge-storm'),
  },
  {
    slug: '05-bloom-after',
    number: '05',
    title: '盛放之后',
    englishTitle: 'After Bloom',
    chapter: 'cycle',
    width: 2444,
    height: 2686,
    alt: '白色骨骼被层层绿色圆叶和红色花朵包围，胸腔间透出荧光黄绿色。',
    short: '花与叶覆盖骸骨，消逝反而成为生长的容器。',
    note: '明亮的绿色与红色环绕骨骼，生命和消逝不再互相排斥。密集的圆叶让画面像一次无法停止的生长。',
    accent: 'green',
    image: image('05-bloom-after'),
  },
  {
    slug: '06-beyond-sea',
    number: '06',
    title: '海底之外',
    englishTitle: 'Beyond the Sea',
    chapter: 'borrowed',
    width: 4096,
    height: 2908,
    alt: '动画角色般的石像与菠萝屋出现在手绘海底景观中。',
    short: '熟悉的动画空间被重新放回纸上，成为个人记忆的一部分。',
    note: '海底场景在黑白线条里变得安静。原本明亮喧闹的世界经过手绘之后，像一段被重新保存的童年记忆。',
    context: '含动画角色视觉元素，作为个人手绘练习呈现。',
    accent: 'ink',
    image: image('06-beyond-sea'),
  },
  {
    slug: '07-resting-tiger',
    number: '07',
    title: '卧虎',
    englishTitle: 'Resting Tiger',
    chapter: 'gaze',
    width: 4096,
    height: 2825,
    alt: '一只老虎侧卧在浅色纸面上，头部转向观众，条纹由密集笔触构成。',
    short: '身体仍在休息，目光却保持警觉。',
    note: '细密的条纹沿着身体展开，力量被收进安静的姿态里。老虎没有逼近，却始终占据观看者的注意。',
    accent: 'ink',
    image: image('07-resting-tiger'),
  },
  {
    slug: '08-night-sea',
    number: '08',
    title: '夜海',
    englishTitle: 'Night Sea',
    chapter: 'prologue',
    width: 4029,
    height: 4096,
    alt: '黑白线描中，巨大月亮悬在波浪起伏的海面上，远处有一根细长的竖线。',
    short: '一根微小的竖线站在巨大的月与海之间。',
    note: '月亮、海浪和远处的细线共同建立展览的第一种尺度：人在广阔世界里很小，但仍可以成为方向。',
    accent: 'blue',
    image: image('08-night-sea'),
  },
  {
    slug: '09-autumn-moon',
    number: '09',
    title: '中秋赏月图',
    englishTitle: 'Autumn Moon',
    chapter: 'cycle',
    width: 4096,
    height: 2590,
    alt: '淡墨圆月中伸入一枝细密树枝，右侧竖写“中秋赏月团圆图”。',
    short: '枝条切入圆月，留白让团圆变得安静。',
    note: '圆形把目光聚拢，枝条又把它轻轻打散。传统意象被处理得克制，像一次停留很久的呼吸。',
    accent: 'ink',
    image: image('09-autumn-moon'),
  },
  {
    slug: '10-black-cat',
    number: '10',
    title: '托起夜色',
    englishTitle: 'Holding the Night',
    chapter: 'gaze',
    width: 4073,
    height: 4096,
    alt: '两只穿长袖的手把一只黑猫从下方托起，黑猫睁眼直视观众。',
    short: '一只黑猫被双手托起，像把夜色举到眼前。',
    note: '猫的身体几乎成为一整块黑色，只有眼睛和手的明度把它从背景中托出。亲近与陌生同时发生。',
    accent: 'ink',
    image: image('10-black-cat'),
  },
  {
    slug: '11-running-rabbit',
    number: '11',
    title: '奔向梦境',
    englishTitle: 'Running into a Dream',
    chapter: 'gaze',
    width: 4096,
    height: 3057,
    alt: '一只由黑色和蓝色短线构成的兔子向右奔跑，周围散布星形与文字涂鸦。',
    short: '蓝黑笔触让兔子从纸面奔出，边缘仍保留着速度。',
    note: '密集短线没有封闭轮廓，而是让身体保持振动。它像在追逐什么，也像刚刚从梦里逃出来。',
    accent: 'blue',
    image: image('11-running-rabbit'),
  },
  {
    slug: '12-hidden-face',
    number: '12',
    title: '遮面者',
    englishTitle: 'Hidden Face',
    chapter: 'gaze',
    width: 2787,
    height: 4096,
    alt: '长发人物用两只手遮住大部分面孔，深色笔触覆盖脸、头发和衣服。',
    short: '双手遮住表情，密集笔触留下无法说出的情绪。',
    note: '脸并没有彻底消失：眼、手指和衣褶仍在互相挤压。越是遮挡，画面越显得靠近。',
    accent: 'ink',
    image: image('12-hidden-face'),
  },
  {
    slug: '13-lone-tree',
    number: '13',
    title: '湖边孤树',
    englishTitle: 'Lone Tree by the Lake',
    chapter: 'cycle',
    width: 3882,
    height: 2698,
    alt: '黑白线描中，一棵向湖面弯曲的树立在前景，远处是水面和连绵群山。',
    short: '树向湖面倾斜，水与群山把时间拉得很长。',
    note: '画面几乎没有事件，只有线条的方向不断改变。树、水和山共同把观看带回一种缓慢的安静。',
    accent: 'ink',
    image: image('13-lone-tree'),
  },
  {
    slug: '14-self-mockery',
    number: '14',
    title: '自嘲',
    englishTitle: 'Self-Mockery',
    chapter: 'borrowed',
    width: 3678,
    height: 2574,
    alt: '鲁迅的黑白肖像占据右侧，左侧写有《自嘲》诗句并画出手持香烟的姿态。',
    short: '肖像、手势与文字共同构成一张沉静而坚定的纸上纪念。',
    note: '大面积黑白对比把人物压缩成有力的形状，诗句则为画面增加另一种节奏：读与看在同一页发生。',
    context: '根据鲁迅肖像与《自嘲》文本进行的纸本创作。',
    accent: 'ink',
    image: image('14-self-mockery'),
  },
  {
    slug: '15-sunflowers',
    number: '15',
    title: '三朵向日葵',
    englishTitle: 'Three Sunflowers',
    chapter: 'borrowed',
    width: 3381,
    height: 4096,
    alt: '三朵橙黄色向日葵插在蓝色花瓶中，绿色叶片由彩色线条描绘。',
    short: '颜色从墨线中突然醒来，三朵花把观看带向明亮处。',
    note: '蓝、绿与橙黄被一层层画进纸面。它既是对经典静物的回应，也保留着直接而个人的手绘温度。',
    context: '向静物画传统与梵高的向日葵意象致意。',
    accent: 'green',
    image: image('15-sunflowers'),
  },
  {
    slug: '16-starry-night',
    number: '16',
    title: '星夜练习',
    englishTitle: 'Study after The Starry Night',
    chapter: 'borrowed',
    width: 1410,
    height: 1080,
    alt: '蓝紫色旋涡状夜空中悬着红色星月，前景有高耸深色柏树与远处村庄。',
    short: '旋转的蓝紫色线条把夜空变成可以被重新描摹的记忆。',
    note: '熟悉的星夜经过另一只手重新出现。笔触并不隐藏临摹的过程，反而把学习、观看与再创造放在同一张纸上。',
    context: '根据梵高《星月夜》进行的手绘练习。',
    accent: 'blue',
    image: image('16-starry-night'),
  },
];

export const chapters = [
  {
    id: 'gaze',
    number: '01',
    title: '凝视',
    english: 'THE GAZE',
    intro: '当你看向画面，画面里的眼睛、动物和人物也在看向你。',
    slugs: ['03-blue-eyes', '10-black-cat', '11-running-rabbit', '07-resting-tiger', '12-hidden-face'],
  },
  {
    id: 'borrowed',
    number: '02',
    title: '借来的世界',
    english: 'BORROWED WORLDS',
    intro: '游戏、动画、文学人物与名画进入纸面，也进入个人记忆。',
    slugs: ['01-panel-city', '06-beyond-sea', '14-self-mockery', '15-sunflowers', '16-starry-night'],
  },
  {
    id: 'cycle',
    number: '03',
    title: '生长与消逝',
    english: 'GROWTH / AFTERLIFE',
    intro: '花、骨骼、月、树、水与风景，沿着同一条线完成循环。',
    slugs: ['02-fractured-rose', '05-bloom-after', '09-autumn-moon', '04-bridge-storm', '13-lone-tree'],
  },
] as const;

export function getWork(slug: string) {
  return works.find((work) => work.slug === slug);
}
